development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: modnotebooks_development

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: modnotebooks_test

# staging:
# https://postgres.heroku.com/databases/heroku-postgres-73fb7fda-copper
