development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mod_development

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mod_test

production:
  adapter: postgresql
  encoding: unicode
  database: mod_production
  pool: 5
  username: mod
  password:
